version: 0.2
phases:
  install:
    commands:
      # CodeBuild should run this first:
      - echo "Changing directory to Myapp"
      - cd Myapp
      - echo "Starting npm install..."
      - npm install
# ... (rest of the file defining pre_build, build, post_build, and artifacts)
