version: 0.2
# -----------------------------------------------------------------------------
# CodeBuild Build Specification
# FIX: Ensure appspec.yml and all deployment files are packaged correctly.
# -----------------------------------------------------------------------------

phases:
  install:
    commands:
      # Install ALL required dependencies for the app, so only PM2 needs attention later.
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Build phase complete."

artifacts:
  files:
    # CRITICAL FIX 1: Package appspec.yml from the Myapp/ source directory
    - Myapp/appspec.yml
    # CRITICAL FIX 2: Package all scripts from the Myapp/scripts/ source directory
    - Myapp/scripts/**
    # Package all application files (app.js, package.json, etc.)
    - Myapp/app.js
    - Myapp/package.json
  # CRITICAL FIX 3: Discard the 'Myapp/' path prefix so all files land in the artifact root.
  discard-paths: yes 
  base-directory: .
