version: 0.2
phases:
  install:
    commands:
      # 1. Navigate to the application root
      - echo "Changing directory to Myapp"
      - cd Myapp
      # 2. Install dependencies (now inside Myapp)
      - echo "Starting npm install..."
      - npm install

  pre_build:
    commands:
      - echo "Pre-build checks complete."
      
  build:
    commands:
      # FIX: Removed 'npm run build' which was causing the failure, 
      # as your package.json does not contain a 'build' script.
      - echo "Skipping application build (Node.js backend)."
      
  post_build:
    commands:
      - echo "Build completed. Preparing CodeDeploy artifact."

artifacts:
  # FIX: Set base-directory to the current directory ('.') which is 'Myapp' 
  # This packages the source code, node_modules, appspec.yml, and scripts/ for CodeDeploy.
  base-directory: .
  files:
    - '**/*'
