version: 0.0
os: linux
files:
  # FIX: Changing source from 'Myapp/' to '/' to assume the contents of Myapp
  # are already at the root of the CodeBuild artifact zip file.
  # This should force the copy of app.js, package.json, and the scripts folder.
  - source: /
    destination: /home/ec2-user/myapp
permissions:
  - object: /home/ec2-user/myapp
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type:
      - file
      - directory
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user
