version: 0.0
os: linux
files:
  # FIX: Change source to 'Myapp/' to correctly target the application code 
  # contained within the 'Myapp' folder inside the artifact root.
  - source: Myapp/
    destination: /home/ec2-user/myapp
permissions:
  - object: /home/ec2-user/myapp
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    type:
      - file
      - directory
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
