version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on `date`
      - echo Building the Docker image...
  build:
    commands:
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build phase completed
      - echo Pushing the Docker images...
      - echo Writing image definitions file...

artifacts:
  files:
    - '**/*'
  name: MySampleApp-$(date +%Y-%m-%d)

cache:
  paths:
    - '/root/.npm/**/*'
